version: 0.2

env:
  variables:
    SONAR_VER: sonar-scanner-cli-4.0.0.1744-linux
    SONAR_HOME: /opt/sonar-scanner
    # PATH: $PATH:$SONAR_HOME/bin

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Install started on `date`
      - test -d $SONAR_HOME && echo skip install sonar || apt-get install --no-install-recommends -y wget unzip
      - test -d $SONAR_HOME || cd /tmp
      - test -d $SONAR_HOME || wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/${SONAR_VER}.zip
      - test -d $SONAR_HOME || unzip ${SONAR_VER}.zip
      - test -d $SONAR_HOME || mv sonar-scanner-*-linux $SONAR_HOME
  build:
    commands:
      - echo Build started on `date`
      - export PATH=${PATH}:${SONAR_HOME}/bin
      - sonar-scanner -h

cache:
  paths:
    - '/opt/sonar-scanner/**/*'
