version: 0.2

phases:
  build:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Build started on `date`
  post_build:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Build completed on `date`
